### ISSUE TITLE
Replace /add, /edit, /delete endpoints with POST, UPDATE/PATCH, and DELETE methods

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#14]
Rather than having multiple endpoints for aoi and export operations such as `add`, `edit`, and `delete`, use HTTP methods of `POST`, `UPDATE` (or `PATCH`), and `DELETE` to describe the operations.

- [x] `GET /aoi/add` becomes `POST /aoi`
- [x] `GET /aoi/edit/:pk` becomes `UPDATE /aoi/:pk` (perhaps `PATCH`)
- [x] `GET /aoi/delete/:pk` becomes `DELETE /aoi/:pk`
- [x] `GET /aoi/:pk/generate/pointcloud` becomes `POST /export` (or `POST /aoi/:pk/export`)
- [x] `GET /aoi/:pk/generate/raster` becomes `POST /export` (or `POST /aoi/:pk/export`)
- [x] `GET /export/edit/:pk` becomes `UPDATE /export/:pk` (perhaps `PATCH`)
- [x] `GET /export/delete/:pk` becomes `DELETE /export/:pk`

**Comment by AlexMountain** [comment]
v3 has been updated with the appropriate GET/POST/PATCH/DELETE http methods for all AOI and export calls.
