### ISSUE TITLE
Add ability to list tasks, possibly filtered by task_state

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#15]
In addition to the existing `/task/:task_id` endpoint, add endpoint to list all user tasks

- [x] `/tasks`

optionally filtered by `task_state` (i.e., `SUCCESS`, `FAILED`, `QUEUED`)

- [x] `/tasks?state=QUEUED`

**Comment by AlexMountain** [comment]
`/tasks` endpoint has been added for v3 and is filterable by `state`
