### ISSUE TITLE
Add ability to query for products intersecting a given geometry, filtered by type

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#16]
The v2 API already has `/product/:pk` to query a particular pointcloud or raster product (presumably vectors are coming too).

Although you could argue that this is redundant with what WFS already provides, the following endpoint could be useful to users.

`/product?geom=<valid WKT geometry>&type=<pointcloud | raster | vector>`

Also, `/aoi?geom=<valid WKT geometry>` already gives us intersecting products, so why would this be useful? Perhaps so that users could check for available data prior to creating the AOI to start with.

**Comment by AlexMountain** [comment]
```/product?geom=<valid WKT geometry>&type=<pointcloud | raster>``` has been added to v3 and returns an array of intersecting product object dicts.
