### ISSUE TITLE
GRiD API should support OAuth 2.0

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#17]
GRiD and apps that use its API should not share passwords. GRiD should be able to revoke tokens for an individual user or for an entire app. GRiD should use an approach that is considered industry standard and is familiar to application developers.

**Comment by msmitherdc** [comment]
@chambbj you should not share passwords. Each user has their own account and password.

**Comment by chambbj** [comment]
@msmitherdc I mean in the sense that the app should not have to prompt the user for their GRiD username and password. It would be nice if the app could redirect to GRiD for user consent and issue a token at that point.

**Comment by AlexMountain** [comment]
I have implemented OAuth2 using the Authentication Code grant type for the GRiD API v3+.  I will leave this open for the time being in case there are any issues or further discussions around OAuth to be had.

**Comment by AlexMountain** [comment]
OAuth2 is a go.  Closing this one.
