### ISSUE TITLE
Long running tasks should provide callback option

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#18]
A new, optional parameter `callback_url` should be supported, that reports back to the caller when processing has completed (success or failure) for long running tasks such as export generation. Response should be a JSON-encoded export object, which already includes `pk` of the export, `task_id`, and `status`, along with full information of the exported dataset, thus obviating the need to reach back in through the API to gather such data, at least for successful exports. For failed exports, the user can ping the `/task` endpoint to retrieve any available `task_traceback`.

**Comment by chambbj** [comment]
Some models to consider:

- https://developer.paypal.com/docs/api/webhooks/

- https://github.com/zapier/django-rest-hooks

**Comment by AlexMountain** [comment]
I've implemented django-rest-hooks for v3 of the API.  Currently it supports subscribing to newdata notifications and export completion notifications, but at a global level instead of individual.

Is that sufficient or should we discuss callbacks at an individual export parameter as well?

If there are any other GRiD features that you would like callbacks for feel free to include them here.

**Comment by chambbj** [comment]
newdata and export completion were the obvious use cases.

Not sure what you mean by "global". Like _every_ event global? Or every event related to my registered application? If the latter, I think that's fine. The application can filter out which AOI received newdata, which export completed, etc. If you mean truly global, that seems like overkill.

**Comment by AlexMountain** [comment]
Yeah sorry let me clarify.  It only applies to your user.  So if you register for a newdata.loaded event, you'll get a notification any time one of your AOIs intersects a new data load.  Likewise if you register for export.complete, you'll be notified for all of your own exports that finish (success or failure).

**Comment by AlexMountain** [comment]
Webhook callbacks have been added to v3 via the hook endpoint.  They support global events for the user or can be narrowed down to only trigger for specific AOIs for the user.
