### ISSUE TITLE
Swagger Docs for v3

### ISSUE THREAD

**Issue by AlexMountain** [CRREL/GRiD-API#20]
- [x] Create and update a Swagger YAML spec for v3 of the GRiD-API.
- [x] Include reference/link to the GRiD-API repo to inform uses of it's existence.

**Comment by chambbj** [comment]
Started a branch for this at https://github.com/CRREL/GRiD-API/tree/v3.

**Comment by AlexMountain** [comment]
swagger.v3.yaml is available on master.
