### ISSUE TITLE
Mismatched types for HSRS and VSRS

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#31]
Both HSRS and VSRS are documented as being integers, but are currently returned in v3 as strings. I think the original assumption was that these (HSRS anyway) would simply be EPSG codes, but maybe this was a bad assumption.

https://github.com/CRREL/GRiD-API/blob/ace7e22c80bbb18117a60269ba4af410352db4da/swagger.v3.yaml#L1482-L1484

https://github.com/CRREL/GRiD-API/blob/ace7e22c80bbb18117a60269ba4af410352db4da/swagger.v3.yaml#L1868-L1870

Note that these also pop up in other endpoints (though they don't use the same Swagger definition).

**Comment by AlexMountain** [comment]
Yeah these were intended to return as int EPSG code representations.  In the future I think we'll want to move to a longer form spatial reference return as strings but for now I am fixing in the v3 API to return ints in the GRiD 1.4.3.1 patch.
