### ISSUE TITLE
Optional and filtered intersection returns

### ISSUE THREAD

**Issue by chambbj** [CRREL/GRiD-API#32]
Querying `/aois` can be quite slow when users have large numbers of AOIs, as GRiD is testing for intersections with assets on the backend. It may make good sense to make this optional, if a user simply wants an overview of their AOIs. They could then test for intersections in a subsequent call to `/aois/{pk}`, or perhaps by hitting the `/products` endpoint directly with their AOI geometry.

**Comment by AlexMountain** [comment]
Current plan is to have additional options for this available in v4, but they could probably be backported to v3 without much effort as another enhancement if there was interest.  I'm including ways to omit geoms and intersections from all the returns that contain these fields as they have the ability to be much larger or require more time to calculate.  Sorting options are also being added for any fields where it makes sense (pks, names, dates, etc).

**Comment by AlexMountain** [comment]
This has been added as a feature to v3.  The following query parameters have been added to the v3 AOI endpoints:
```
intersections: bool, whether or not to return the product intersections.
intersection_types: string, comma separated list of product types to return.  Returns all types by default.
intersection_geoms: bool, whether or not to return the geometries of the product intersections.
```

The following query parameters have been added to the v3 Product endpoints:
```
geoms: bool, whether or not to return the geometry of the product.
type: string, now accepts a comma separated list of product types to return.  Returns all types by default.
```

Defaults for these options should match the current v3 returns.  These enhancements will be live with GRiD's 1.4.5 release.
